### ISSUE TITLE
Pseudo mixin spelled incorrectly

### ISSUE THREAD

**Issue by jvlahos** [Upstatement/upbase#17]
The mixin is currently spelled `psuedo`, instead of `pseudo`. Someone else probably understand repercussions better than me — would we need to have both spellings for the time being if we wanted to correct it? 

https://github.com/Upstatement/upbase/blob/master/components/_mixins.scss#L422

**Comment by t1to98** [comment]
This was addressed by commit 9c1ed08 (referenced above). The current solution is to support both the correct and incorrect spellings of `pseudo` ... or is it `psuedo`?
