### ISSUE TITLE
Remove Compass dependencies & copy examples to CodePen 

### ISSUE THREAD

**Issue by t1to98** [Upstatement/upbase#24]
Per our discussion during today's CSS Share, we're going to divide and conquer to make a long-awaited change to Upbase and kill several birds with one stone. Here's the plan.

1. Pick a mixin (or take the one you're assigned) 
2. Copy a working example to [CodePen](http://codepen.io/upstatement/), demonstrate use case 
3. Remove Compass dependencies
4. Share link to final CodePen example here

#### Helpers
- [x] Input Defaults - @andyrader 
- [ ] SVG Fallback Pattern - @andyrader   
- [x] Retina Background Images - @NathanHass 

#### Layout
- [x] Media Grid - @t1to98
- [x] Grid Static - @sdasse 
- [ ] UI Grid 2
- [ ] UI Grid RL
- [ ] UI Grid LR
- [ ] UI Grid 3
- [ ] UI Grid RRL
- [ ] UI Grid 4
- [ ] UI Grid 5
- [x] Cols - @jvlahos 
- [ ] Pair - @t1to98

**Comment by jvlahos** [comment]
Consolidating into Issue #25
