### ISSUE TITLE
Map out proposed upbase framework

### ISSUE THREAD

**Issue by jvlahos** [Upstatement/upbase#5]
Could someone (perhaps @mswartz is best candidate) create some sort of visual map or documentation of the new upbase framework -- the new way / the old way, how the parts come together, where they come from, what parts will hold what pieces, what tools are involved and what their purpose will be, what's missing or unknown, etc. Big picture stuff. (Or alternatively, schedule a roundtable to discuss)

I feel like I could be more helpful to the effort if there was some sort of tentative, working roadmap or documentation.

**Comment by t1to98** [comment]
Cleaning out old issues that aren't relevant at the moment.
